### ISSUE TITLE
Prettify and fix formatting for site

### ISSUE THREAD

**Issue by ghost** [CSI-280/primeorcas#28] opened 2020-01-28 01:08 UTC

**Comment by NaomiHoniker** [comment] 2020-02-08 23:59
I know I'm not assigned to this, but I took a shot at making the slideshow on Locate actually work. It still doesn't, but I figured out where the issue is. It's something with style.display on line 94. I think the CSS and HTML should be fine, it's just something weird with the JS.

**Closed as completed** 2020-02-12 23:44 UTC
